version: '3.8'

services:
  zookeeper: # Kafka 的元件設計依賴 Zookeeper 來做叢集協調
    image: confluentinc/cp-zookeeper:7.6.1
    restart: unless-stopped
    container_name: zookeeper_container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - simulation_test_connection

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    restart: unless-stopped
    container_name: kafka_container
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"    # 給外部客戶端連線
      - "29092:29092"  # 給內部 docker network 連線
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - simulation_test_connection


  mongo:
    image: mongo:7
    restart: unless-stopped
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - './mongo_data:/data/db'
    networks:
      - simulation_test_connection

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    container_name: mongo_express_container
    ports:
      - "27018:8081"
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${ME_CONFIG_MONGODB_ENABLE_ADMIN}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongo


  redis:
    image: redis:7
    restart: unless-stopped
    container_name: redis_container
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - './redis_data:/data'
    networks:
      - simulation_test_connection

  redis_insight:
    image: redis/redisinsight:latest
    restart: unless-stopped
    container_name: redis_insight_container
    ports:
      - "6380:5540"
    environment:
      REDISINSIGHT_HOST: 0.0.0.0 # 存取 Redis 服務，必須設置這個變數
    volumes:
      - './redis_insight_data:/db'
    depends_on:
      - redis


networks:
  simulation_test_connection:
    driver: bridge